# Generated by Django 5.1.4 on 2024-12-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_filter_price_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Old', 'Old'), ('OUT OF STOCK', 'OUT OF STOCK')], max_length=100),
        ),
    ]
