# Generated by Django 5.1.4 on 2024-12-19 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0005_alter_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='additional_info',
        ),
    ]
