# Generated by Django 5.1.4 on 2025-01-13 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0011_wallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
