# Generated by Django 5.1.4 on 2025-01-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0013_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
