# Generated by Django 5.1.4 on 2025-01-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0015_categoryoffer_productoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_amount',
            field=models.CharField(max_length=10),
        ),
    ]
