# Generated by Django 5.1.4 on 2025-01-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0017_alter_coupon_code_alter_coupon_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='discount_percentage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='discount_percentage',
            field=models.IntegerField(),
        ),
    ]
