# Generated by Django 5.1.4 on 2025-02-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0023_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Return Requested', 'Return Requested'), ('Return Accepted', 'Return Accepted'), ('Payment Failed', 'C')], default='Pending', max_length=54),
        ),
    ]
