# Generated by Django 5.1.4 on 2025-02-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0024_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Return Requested', 'Return Requested'), ('Return Accepted', 'Return Accepted'), ('Payment Failed', 'Payment Failed')], default='Pending', max_length=54),
        ),
    ]
